### ISSUE TITLE
Vocabulary tokens?

### ISSUE THREAD

**Issue by wjgan7** [shuzi/insuranceQA#2]
Are variations with punctuation of a certain word (e.g. "titles.", "titles,") intentional? It seems like there is a lot of redundancy.

**Comment by shuzi** [comment]
There are two versions (raw text and tokenized text).
In raw text, "titles.", "titles," are treated as different two vocaburaries.

**Comment by hfsugar** [comment]
Hello, does it support Chinese? Thanks.

**Comment by shuzi** [comment]
@hfsugar    No.  It is an English corpus.
