### ISSUE TITLE
what is Pool data

### ISSUE THREAD

**Issue by hailiang-wang** [shuzi/insuranceQA#4]
In the README.md, Pool is mentioned at ```Pool is generated by SOLR```. 
I haven't check the data yet, but based on my understanding, pool data is retrieved with Solr system and it is the questions array list when query with the question in the first column. Is it?
```
<Domain><TAB><QUESTION><TAB><Groundtruth>
```

So, Groundtruth is the answer's label. Pool is the similar questions that return from Solr.

**Comment by hailiang-wang** [comment]
After checking the data, it seems Groundtruth do have multi answers, why is that? Does the answers share the same meaning on behalf of the question?

**Comment by shuzi** [comment]
After the question was raised, it is possible that more than one domain expert have answered that questions.
